### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by kumavis** [kumavis/voxel-backup#1]
```
╭─{  } kumavis in ~/Development/node/voxel/voxel-backup on (master)
╰─○ npm start

> voxel-backup@0.0.0 start /Users/kumavis/Development/Node/Voxel/voxel-backup
> node demo.js

Using database "/Users/kumavis/Development/Node/Voxel/voxel-backup/dump/kumavis"
Using server "ws://voxel.kumavis.me:8000/"
emitter initialized

events.js:72
        throw er; // Unhandled 'error' event
              ^
SyntaxError: Error parsing peer data: Unexpected end of input
    at Object.parse (native)
    at Stream.parseJSON (/Users/kumavis/Development/Node/Voxel/voxel-backup/node_modules/duplex-emitter/parser.js:14:18)
    at Stream.stream.write (/Users/kumavis/Development/Node/Voxel/voxel-backup/node_modules/duplex-emitter/node_modules/through/index.js:26:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.EventEmitter.emit (events.js:95:17)
    at drain (/Users/kumavis/Development/Node/Voxel/voxel-backup/node_modules/duplex-emitter/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/Users/kumavis/Development/Node/Voxel/voxel-backup/node_modules/duplex-emitter/node_modules/through/index.js:45:5)
    at emit (/Users/kumavis/Development/Node/Voxel/voxel-backup/node_modules/duplex-emitter/node_modules/split/index.js:35:14)
    at next (/Users/kumavis/Development/Node/Voxel/voxel-backup/node_modules/duplex-emitter/node_modules/split/index.js:44:7)
    at Stream.<anonymous> (/Users/kumavis/Development/Node/Voxel/voxel-backup/node_modules/duplex-emitter/node_modules/split/index.js:49:5)
```

**Comment by kumavis** [comment]
the input seems to be: `[`
wtf?

**Comment by kumavis** [comment]
using [websocket.org](http://www.websocket.org/echo.html) I got this data:

```
CONNECTED
RESPONSE: [ ["id","b03bae982f88b96b2db1007a7275f3c6"]
RESPONSE: , ["settings",{"chunkDistance":2,"materials":[["grass","dirt","grass_dirt"],"dirt","plank","cobblestone","brick","bedrock","glowstone","netherrack","obsidian","diamond","whitewool","redwool","bluewool"],"texturePath":"../painterly-textures/textures/","worldOrigin":[0,0,0],"controls":{"discreteFire":true},"avatarInitialPosition":[2,20,2],"generateChunks":true,"generatorToString":"function (i,j,k) {\n return j <= 16 * Math.exp(-(i*i + k*k) / 64) ? 1 : 0;\n}"}]
RESPONSE: , ["update",{"positions":{"b03bae982f88b96b2db1007a7275f3c6":{"position":{"x":0,"y":0,"z":0},"rotation":{"x":0,"y":0}}},"date":1379822896331},null,null]
RESPONSE: , ["update",{"positions":{"b03bae982f88b96b2db1007a7275f3c6":{"position":{"x":0,"y":0,"z":0},"rotation":{"x":0,"y":0}}},"date":1379822896379},null,null]
RESPONSE: , ["update",{"positions":{"b03bae982f88b96b2db1007a7275f3c6":{"position":{"x":0,"y":0,"z":0},"rotation":{"x":0,"y":0}}},"date":1379822896427},null,null]
RESPONSE: , ["update",{"positions":{"b03bae982f88b96b2db1007a7275f3c6":{"position":{"x":0,"y":0,"z":0},"rotation":{"x":0,"y":0}}},"date":1379822896475},null,null]
<truncated>
```

**Comment by kumavis** [comment]
the original `voxel-client` is using a honking old version of duplex-emitter
`0.1.10` vs `2.1.2`
